services:
  - type: web
    name: cerebro-energia-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn cerebro_energia.wsgi:application
    pythonVersion: 3.12.3
